name: Build Packer AMI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm install

      - name: Create ZIP artifact
        run: |
          zip -r webapp.zip * -x "*.git*" ".github/*" ".gitignore" "README.md" "tests/*" "packer/*" "node_modules/*"
      
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: webapp
          path: webapp.zip
          
  build_ami:
    name: "Packer Build AMI"
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: "Configure AWS Credentials"
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: webapp

    - name: Install Packer
      run: sudo apt-get install -y packer

    - name: Initialize Packer
      run: packer init ./packer/aws.pkr.hcl

    - name: Build Packer Image
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
        INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        AMI_NAME: ${{ secrets.AMI_NAME }}
        VOLUME_SIZE: ${{ secrets.VOLUME_SIZE }}
        VOLUME_TYPE: ${{ secrets.VOLUME_TYPE }}
        DEMO_ACCOUNT_ID: ${{ secrets.DEMO_ACCOUNT_ID }}
      run: |
        packer build \
          -var "aws_region=${AWS_REGION}" \
          -var "aws_source_ami=${AWS_SOURCE_AMI}" \
          -var "instance_type=${INSTANCE_TYPE}" \
          -var "ssh_username=${SSH_USERNAME}" \
          -var "ami_name=${AMI_NAME}" \
          -var "volume_size=${VOLUME_SIZE}" \
          -var "volume_type=${VOLUME_TYPE}" \
          -var "demo_account_id=${DEMO_ACCOUNT_ID}" \
          ./packer/aws.pkr.hcl
          