name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer_check:
    name: "Packer Format and Validation Check"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Packer
      run: sudo apt-get install -y packer

    - name: Initialize Packer
      run: packer init ./packer/aws.pkr.hcl

    - name: Run Packer Fmt
      run: packer fmt -check -diff ./packer/aws.pkr.hcl

    - name: Run Packer Validate
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_SOURCE_AMI: ${{ secrets.AWS_SOURCE_AMI }}
        INSTANCE_TYPE: ${{ secrets.INSTANCE_TYPE }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        AMI_NAME: ${{ secrets.AMI_NAME }}
        VOLUME_SIZE: ${{ secrets.VOLUME_SIZE }}
        VOLUME_TYPE: ${{ secrets.VOLUME_TYPE }}
        DEMO_ACCOUNT_ID: ${{ secrets.DEMO_ACCOUNT_ID }}
      run: |
        run: |
        # Create a dummy webapp.zip file for validation since webapp.zip doesn't exist until merge
        touch placeholder.txt
        zip webapp.zip placeholder.txt

        packer validate \
          -var "aws_region=${AWS_REGION}" \
          -var "aws_source_ami=${AWS_SOURCE_AMI}" \
          -var "instance_type=${INSTANCE_TYPE}" \
          -var "ssh_username=${SSH_USERNAME}" \
          -var "ami_name=${AMI_NAME}" \
          -var "volume_size=${VOLUME_SIZE}" \
          -var "volume_type=${VOLUME_TYPE}" \
          -var "demo_account_id=${DEMO_ACCOUNT_ID}" \
          ./packer/aws.pkr.hcl
          
